name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '2.5'
          - '2.6'
          - '2.7'
          - '3.0'
          - '3.1'
          - '3.2'
          - '3.3'
          - '3.4'
        include:
          # Use older bundler for Ruby < 3.1 to avoid compatibility issues
          - ruby: '2.5'
            bundler: '2.3.26'
          - ruby: '2.6'
            bundler: '2.3.26'
          - ruby: '2.7'
            bundler: '2.3.26'
          - ruby: '3.0'
            bundler: '2.3.26'

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          bundler: ${{ matrix.bundler }}
      - name: Run the default task
        run: bundle exec rake
